# Site settings
title: Seven
email: chuqi77@gmail.com
description: "Programming, Gaming And Computing"
baseurl: ""
url: "chuzui.github.io"
twitter_username:
github_username:  chuzui

# Build settings
markdown: kramdown
permalink: pretty
